const $=s=>document.querySelector(s);let mode="today";let coords=null;
const lore=["BEAN LORE #7: The humble bean requires no API key.","BEANS ACQUIRED (potential).","No beans? Suspicious.","Legumes are infrastructure.","The goblin checks hours before celebrating."];
function say(s){$("#state").textContent=s;$("#lore").textContent=lore[Math.floor(Math.random()*lore.length)]}
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.filter});
$("#locate").onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};$("#where").value="Current location";say("Coordinates acquired. Goblin is sniffing for provisions.")},()=>say("Location permission was not granted. Enter a ZIP or city instead.")):say("This browser does not provide location.");
$("#hunt").onclick=async()=>{const q=$("#where").value.trim();if(!q&&!coords)return say("Goblin needs a location first.");say("Searching public food-resource listings…");$("#results").innerHTML="";
try{let loc=coords;if(!loc){const g=await fetch("https://nominatim.openstreetmap.org/search?format=json&limit=1&q="+encodeURIComponent(q),{headers:{"Accept":"application/json"}}).then(r=>r.json());if(!g.length)throw Error("location");loc={lat:+g[0].lat,lon:+g[0].lon}}
const query='[out:json][timeout:15];(node["amenity"="food_bank"](around:16093,'+loc.lat+','+loc.lon+');way["amenity"="food_bank"](around:16093,'+loc.lat+','+loc.lon+');node["social_facility"="food_bank"](around:16093,'+loc.lat+','+loc.lon+');way["social_facility"="food_bank"](around:16093,'+loc.lat+','+loc.lon+'););out center tags;';
const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),22000);
const r=await fetch("/api/pantries?lat="+encodeURIComponent(loc.lat)+"&lon="+encodeURIComponent(loc.lon),{signal:controller.signal});clearTimeout(timer);
if(!r.ok)throw Error("pantry service "+r.status);const d=await r.json();render((d.elements||[]).concat((d.seeds||[]).map((z,i)=>({id:"seed"+i,tags:{name:z.name,"addr:full":z.address,phone:z.phone||"",opening_hours:z.hours||"",website:z.sourceUrl||"",source:z.source||"",confidence:z.confidence||""}}))),loc)
catch(e){say("Live search failed. Goblin refuses to invent pantry hours. Try again shortly.")}};
function render(items,loc){const uniq=[...new Map(items.map(x=>[(x.tags?.name||"")+"|"+(x.tags?.["addr:street"]||x.id),x])).values()];if(!uniq.length)return say("No mapped food banks found within about 10 miles. This does not mean none exist — try 211 or a local food bank directory.");
$("#state").textContent=uniq.length+" mapped food resources found. Verify hours before traveling.";
$("#results").innerHTML=uniq.map(x=>{let t=x.tags||{},lat=x.lat||x.center?.lat,lon=x.lon||x.center?.lon,name=t.name||"Food resource",phone=t.phone||t["contact:phone"]||"",web=t.website||t["contact:website"]||"",hours=t.opening_hours||"Hours not published",addr=t["addr:full"]||[t["addr:housenumber"],t["addr:street"],t["addr:city"]].filter(Boolean).join(" ")||"See map";return '<article class="card"><h3>'+esc(name)+'</h3><div class="meta">'+esc(hours)+'</div><p>'+esc(addr)+'</p><div class="verify">⚠ Verify hours and eligibility before traveling.</div><div class="actions">'+(phone?'<a href="tel:'+encodeURIComponent(phone)+'">CALL</a>':'')+(lat?'<a href="https://www.google.com/maps/search/?api=1&query='+lat+','+lon+'" target="_blank">DIRECTIONS</a>':'')+(web?'<a href="'+escAttr(web)+'" target="_blank">WEBSITE</a>':'')+'</div></article>'}).join("");$("#lore").textContent="BEANS ACQUIRED (potential). Goblin found "+uniq.length+" leads."}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}function escAttr(s){return esc(s).replace(/'/g,"&#39;")}